# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

well_commerce_search:
    search_engine:
        quick_search:
            limit: 20
            order_by: "score"
            order_dir: "asc"
        adapters:
            algolia:
                class: WellCommerce\Component\Search\Adapter\Algolia\AlgoliaSearchAdapter
                configurator: 'algolia.system.configurator'
            elasticsearch:
                class: WellCommerce\Component\Search\Adapter\ElasticSearch\ElasticSearchAdapter
                configurator: 'elasticsearch.system.configurator'
